# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [12]:
# Import torch
import torch

# Create random tensor
x = torch.randn(7, 7)
x

tensor([[ 0.1008,  0.7117, -2.5539,  0.2752,  0.0835,  1.0437,  0.1528],
        [ 0.2079, -1.4077, -0.8599, -1.1899,  1.4651, -1.5333,  0.3329],
        [-0.2968, -0.4342,  0.1887, -0.5199, -0.1564, -0.0468, -2.0871],
        [ 0.4128,  1.1391,  0.0938, -0.3066,  0.5600,  0.1284, -0.3647],
        [-0.1869, -1.2803, -1.1023,  0.5492, -2.5206,  0.4627,  1.8944],
        [-0.1386,  0.1674,  0.1061, -1.0250, -0.7485,  1.2575,  0.1239],
        [-1.3836,  0.8503, -1.8376, -1.0426,  1.3609, -1.9329,  0.1862]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
y = torch.randn(1, 7)
# Perform matrix multiplication 
y_t = torch.transpose(y, 0, 1)
print(torch.matmul(x, y_t))

tensor([[ 1.8039],
        [-2.6211],
        [-1.8241],
        [ 2.6437],
        [-2.6353],
        [-2.2069],
        [ 3.7425]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
seed = 0

# Create two random tensors
torch.manual_seed(seed)
x = torch.rand(7, 7)
torch.manual_seed(seed)
y = torch.rand(1, 7)

# Matrix multiply tensors
print(torch.matmul(y, x))

tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
gpu_seed = 1234
device = "cuda" if torch.cuda.is_available() else "cpu"


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.cuda.manual_seed(gpu_seed)

# Check for access to GPU
print(f"Device is {device}")
# Create two random tensors on GPU
x = torch.rand(2, 3, device=device)
torch.cuda.manual_seed(gpu_seed)
y = torch.rand(2, 3, device=device)
print(x)
print(y)

Device is cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(x, torch.transpose(y, 0, 1))
z

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(torch.max(z))
# Find min
print(torch.min(z))

tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(torch.argmax(z))

# Find arg min
print(torch.argmin(z))

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
seed = 7

# Create random tensor
tensorx = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensory = tensorx.squeeze()

# Print out tensors and their shapes
print(tensorx, tensorx.shape)
print(tensory, tensory.shape)

tensor([[[[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056, 0.5932,
           0.1123, 0.1535]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056, 0.5932, 0.1123,
        0.1535]) torch.Size([10])
